/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RyanZhuEnvironmentGUI;
import my.zhuenvironmentgui.ZhuEnvironmentGUI;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        ZhuEnvironmentGUI.main(args);
    }
}
